pub mod command;
pub mod config;
pub mod connection;
pub mod database;
pub mod frame;
pub mod parse;
pub mod server;
pub mod store;
pub use command::Command;
pub use connection::Connection;
pub use frame::Frame;
pub type Error = Box<dyn std::error::Error + Send + Sync>;
pub type Result<T> = std::result::Result<T, Error>;
